### ISSUE TITLE
MKR NB 1500 Not working with AWS

### ISSUE THREAD

**Issue by ircole** [arduino-libraries/MKRNB#46]
This similar to another post here but a little different.  I have no problem connecting to AZURE but never completes connecting with AWS MQTT.   I've followed the suggestions that I've found but with no success.  I created the csr on the 1500 and copied to AWS.  Maybe this is a firmware issue as was mentioned.  Any help will be appreciated.  Very likely something that I'm missing as I'm not as young as I used to be.  Attached is a file showing what is happening.  The sequence shown repeats over and over.  Appears that it's close to connecting.  I haven't found any logs on AWS that might help, I'm still looking, ignorance isn't always bliss.

[awsconnect2.txt](https://github.com/arduino-libraries/MKRNB/files/4500356/awsconnect2.txt)

**Comment by ircole** [comment]
The problem was me.  I had copied the wrong security file.

**Comment by marcelchelo** [comment]
I'm struggling to connect to aws mqtt, do you have any documentation links that you followed?
