### ISSUE TITLE
detachGPRS

### ISSUE THREAD

**Issue by jtsse** [arduino-libraries/MKRNB#56]
It seems like detachGPRS does not work. The function sets 
```C++
_state = GPRS_STATE_DEATTACH;
```
and calls the ready function to fire the AT command _AT+CGATT=0_.
The ready function waits till there is a response (_GPRS_STATE_WAIT_DEATTACH_RESPONSE_) and sets  __status_  to _IDLE_ if everything was fine. Because in this state ready is never set to 1 again, the ready function stays in an infinite loop, because the function returns zero at the beginning of the function (_if (ready == 0)_).

**Comment by aentinger** [comment]
Fixed by #69.
