### ISSUE TITLE
Endless loop in detachGPRS()

### ISSUE THREAD

**Issue by baender** [arduino-libraries/MKRNB#68]
When using detachGPRS() the program gets caught in an endless loop. While looking a bit into it, I found that the ready() function would not break the loop after case GPRS_STATE_WAIT_DEATTACH_RESPONSE was reached.
In analogy to case GPRS_STATE_WAIT_CHECK_ATTACHED_RESPONSE and case READY_STATE_WAIT_CHECK_REGISTRATION_RESPONSE (in NB.cpp) ready should be set to 1 to leave the function. This is missing for the case of detachGPRS(). After adding this line, the GPRS functions did work properly.
I will add pull request #69 for this issue.

**Comment by aentinger** [comment]
Fixed by #69.
